apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>App 1</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                background-color: #f0f0f0;
                text-align: center;
                padding: 50px;
            }
            h1 {
                color: #df0b0b;
            }
        </style>
    </head>
    <body>
        <h1>Hello from app1</h1>
    </body>
    </html>
