Vagrant.configure("2") do |config|
  # Configuration du contrôleur
  config.vm.define "controller" do |controller|
    controller.vm.box = "debian/bullseye64"
    controller.vm.hostname = "sohemamiS"

    controller.vm.network "private_network", ip: "192.168.56.110", virtualbox__intnet: "gcptest-network"

    controller.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--natnet1", "10.3/16"]
      vb.memory = "1024"
    end

    # Dossier partagé
    controller.vm.synced_folder ".", "/vagrant", disabled: false

    # Provisionnement
    controller.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y curl net-tools
      sudo chmod 777 /vagrant

      # Installer K3s en mode contrôleur
      curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644

      # Sauvegarder le token
      sudo cat /var/lib/rancher/k3s/server/node-token >> /vagrant/token
    SHELL
  end

  # Configuration de l'agent
  config.vm.define "agent" do |agent|
    agent.vm.box = "debian/bullseye64"
    agent.vm.hostname = "sohemamiSW"

    agent.vm.network "private_network", ip: "192.168.56.111", virtualbox__intnet: "gcptest-network"

    agent.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--natnet1", "10.3/16"]
    end

    # Dossier partagé
    agent.vm.synced_folder ".", "/vagrant", disabled: false

    # Provisionnement
    agent.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y curl net-tools
      sudo chmod 777 /vagrant
      
      # Attendre que le token soit disponible
      while [ ! -f /vagrant/token ]; do
          echo "Waiting for token to be created..."
          sleep 2
      done

      # Installer K3s en mode agent
      K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=\$(cat /vagrant/token) sh -c 'curl -sfL https://get.k3s.io | sh -'

      # Supprimer le token après l'installation
      rm -f /vagrant/token
    SHELL
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
  end
end













  
  
  
  
  
  
  
  
  
  
  
  
  


  
  

























